name: "ai_course_dbt"
version: "1.0.0"
config-version: 2

profile: "ai_course_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
docs-paths: ["docs"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ai_course_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
    playground:
      +materialized: view

seeds:
  ai_course_dbt:
    +quote_columns: false
