version: 2

models:
  - name: rpt_country_order_performance
    description: "Daily successful order performance by country with one row per order_date and country."
    columns:
      - name: order_date
        tests:
          - not_null
      - name: country
        tests:
          - not_null
      - name: successful_revenue
        tests:
          - not_null